ostree-base: add image linting

diff --git a/ostree-base/Containerfile b/ostree-base/Containerfile
--- a/ostree-base/Containerfile
+++ b/ostree-base/Containerfile
@@ -65,3 +65,8 @@ ADD files/profile.d/vim-default-editor.sh /etc/profile.d/vim-default-editor.sh
 
 # Enable git prompt
 ADD files/profile.d/git-prompt.sh /etc/profile.d/git-prompt.sh
+
+# Verify image is good (must be run last!)
+RUN rm -rf /var && mkdir /var && \
+    test -f /usr/lib/sysusers.d/screen.conf || echo -e 'g screen 84' > /usr/lib/sysusers.d/screen.conf   # Cleanup image for linting
+RUN bootc container lint --fatal-warnings # Lint the image
